languageCode = "it"
languageName = "Italian"

weight = 1
title = "Home"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "images/menu_logo.png"
# secondaryLogo = "images/logo.png"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "Savior Social Rugby"
image = "images/logo.png"
# headline = "I'm only human"
# bio = "A little bit about you"
links = [
  { instagram = "https://www.instagram.com/saviors_social_rugby" },
  { whatsapp = "https://wa.me/+393297956230" },
  { facebook = "https://www.facebook.com/saviorssocialrugby" },
  { email = "mailto:info@saviorssocialrugby.it" },
]
