# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"   # valid options: light or dark
autoSwitchAppearance = false

enableA11y = false
enableSearch = true
enableCodeCopy = false

replyByEmail = false

# mainSections = ["section1", "section2"]
# robots = ""
homePageVideo = "videos/video.mp4"

disableImageZoom = true
disableImageOptimization = true
disableTextInHeader = true
disableImageOptimizationMD = true
# backgroundImageWidth = 1200

defaultBackgroundImage = "images/logo.png"   # used as default for background images 
defaultFeaturedImage = "images/featured.jpg" # used as default for featured images in all articles
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

# [next_match]
# home = "Saviors Social Rugby"
# home_logo = "saviors.png"
# visitors = "Ravenna Rugby FC"
# visitors_logo = "ravenna.png"
# result = "TBD"
# when_where = "7ᵃ Ritorno Campionato FIR Serie C Regionale 2024/2025 - 04/05/2025 15:30 @ Via Roversano 2815, 47522 - Cesena (FC)"

# [last_match]
# home = "Saviors Social Rugby"
# home_logo = "saviors.png"
# visitors = "Ravenna Rugby FC"
# visitors_logo = "ravenna.png"
# result = "26 - 29"
# when_where = "7ᵃ Ritorno Campionato FIR Serie C Regionale 2024/2025 - 04/05/2025 15:30 @ Via Roversano 2815, 47522 - Cesena (FC)"

#[[sponsors]]
#name = "Smart Security"
#img = "sponsors/smartsecurity.jpg"
#site = "https://www.smartsecurity.srl"

[[sponsors]]
name = "BCC Romagnolo"
img = "sponsors/bcc.png"
site = "https://www.bccromagnolo.it"

# [[sponsors]]
# name = "Legni per api"
# site = "https://www.legniperapi.it"
# img = "sponsors/legniperapi.png"

# [[sponsors]]
# name = "Miele Ligustica"
# img = "sponsors/valdomiele.png"

[[sponsors]]
img = "sponsors/placeholder.png"

[header]
# valid options: basic, fixed, fixed-fill, fixed-fill-blur
layout = "fixed-fill"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = false

[homepage]
layout = "page"                   # valid options: page, profile, hero, card, background, custom
homepageImage = "images/logo.png" # used in: hero, and card
showTitle = false
showRecent = true
showRecentItems = 9
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false      # only used when layout equals background

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "thumbAndBackground"   # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = false
# showRelatedContent = false
# relatedContentLimit = 3
showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
# sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
showZenMode = false

[list]
showHero = false
# heroStyle = "thumbAndBackground"   # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = false
# heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
# heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[buymeacoffee]
# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
