baseURL: 'https://notdodo.github.io/saviors/'
languageCode: it-it
title: Saviors Social Rugby
theme: PaperMod
params:
  env: production
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: Saviors Social Rugby
    imageUrl: '/images/logo.png'
    imageTitle: SaviorsLogo
    imageWidth: 130
    imageHeight: 190
    # buttons:
    #   - name: Archive
    #     url: /archive
    #   - name: Github
    #     url: 'https://github.com/'
  socialIcons:
    - name: Instagram
      url: 'https://www.instagram.com/saviors_social_rugby/'
    - name: Facebook
      url: 'https://www.facebook.com/saviorssocialrugby'
menu:
  main:
    - identifier: calendario
      name: Calendario
      url: /calendario/
      weight: 10
    - identifier: under
      name: Under
      url: /under/
      weight: 20
    - identifier: archivio
      name: Archivio
      url: /archivio/
