baseURL: 'https://notdodo.github.io/saviors/'
languageCode: it-it
title: Saviors Social Rugby
theme: PaperMod
disableKinds:
  - taxonomy
  - taxonomyTerm
  - term
params:
  env: production
  defaultTheme: white
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: Saviors Social Rugby
    imageUrl: '/images/logo.png'
    imageTitle: SaviorsLogo
    imageWidth: 140
    imageHeight: 200
    # buttons:
    #   - name: Archive
    #     url: /archive
    #   - name: Github
    #     url: 'https://github.com/'
  socialIcons:
    - name: Instagram
      url: 'https://www.instagram.com/saviors_social_rugby/'
    - name: Facebook
      url: 'https://www.facebook.com/saviorssocialrugby'
    - name: email
      url: 'mailto:info@saviorssocialrugby.it'
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: contatti
      name: Contatti
      url: /contatti/
      weight: 2
    - identifier: calendario
      name: Calendario
      url: /calendario/
      weight: 3
    - identifier: under
      name: Under
      url: /under/
      weight: 4
    - identifier: archivio
      name: Archivio
      url: /archivio
      weith: 5
