baseURL: "https://notdodo.github.io/saviors/"
languageCode: it-it
title: Saviors Social Rugby
theme: PaperMod
disableKinds:
  - taxonomy
  - taxonomyTerm
  - term

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

params:
  env: production
  defaultTheme: dark
  disableThemeToggle: true
  profileMode:
    enabled: true
    imageUrl: "/images/logo.png"
    imageTitle: SaviorsLogo
    imageWidth: 345
    imageHeight: 585
    # buttons:
    #   - name: Archive
    #     url: /archive
    #   - name: Github
    #     url: 'https://github.com/'
  socialIcons:
    - name: Instagram
      url: "https://www.instagram.com/saviors_social_rugby/"
    - name: Facebook
      url: "https://www.facebook.com/saviorssocialrugby"
    - name: email
      url: "mailto:info@saviorssocialrugby.it"
    - name: whatsapp
      url: https://wa.me/+393297956230
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

imaging:
  hint: icon
  quality: 100
  resampleFilter: MitchellNetravali

menu:
  main:
    # - identifier: home
    #   name: Home
    #   url: /
    #   weight: 1
    - identifier: contatti
      name: Contatti
      url: /contatti/
      weight: 1
    - identifier: calendario
      name: Calendario
      url: /calendario/
      weight: 2
    - identifier: under
      name: Under
      url: /under/
      weight: 3
    - identifier: search
      name: 🔎
      url: /search/
    # - identifier: archivio
    #   name: Archivio
    #   url: /archivio
    #   weith: 5
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
